[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt && rm -rf node_modules package-lock.json .next && npm cache clean --force && npm install --force && npm run build"
  publish = ".next"

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"
  PIP_NO_CACHE_DIR = "1"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "."
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[headers]]
  for = "/data/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" 