[build]
  command = "pip install -r requirements.txt && npm install && npm run build"
  publish = ".next"

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "."
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 