[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt && rm -rf node_modules .next package-lock.json && npm cache clean --force && npm install --force && npm run build"
  publish = ".next"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/**/*"]

[functions.excluded_files]
  patterns = ["*.config.js", "*.config.ts", "next-env.d.ts"]

[functions.environment]
  DEEPSEEK_API_KEY = "sk-4cb4062ffcbb47f898a7f8bd57b01f12"
  LAMBDA_URL = "=https://vfr76hdfy6orj34fdgcpgfnyfa0ibrbo.lambda-url.us-east-2.on.aws/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[dev]
  command = "python api.py"
  port = 8000
  targetPort = 8000
  publish = ".next"
  framework = "#custom" 