[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt && rm -rf node_modules .next package-lock.json && npm cache clean --force && npm install --force && npm run build"
  publish = ".next"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/**/*"]

[functions.excluded_files]
  patterns = ["*.config.js", "*.config.ts", "next-env.d.ts"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" 